### ISSUE TITLE
やること4: メンターのIssueにコメント

### ISSUE THREAD

**Issue by S-Shimotori** [mrkn/mrkn-sezemi-2015-readable-code#1]
[S-Shimotoriです](http://github.com/S-Shimotori)

**Comment by S-Shimotori** [comment]
リポジトリ：[https://github.com/S-Shimotori/S-Shimotori-sezemi-2015-readable-code](https://github.com/S-Shimotori/S-Shimotori-sezemi-2015-readable-code)

**Comment by mrkn** [comment]
リポジトリの場所が分かりました。ありがとうございます！
